OnlineExamPlatform/ViewModels/CourseTransactionViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;
using OnlineExamPlatform.Models;

namespace OnlineExamPlatform.ViewModels
{
    public class CourseTransactionViewModel
    {
        [Required]
        [Display(Name = "Department")]
        public int DepartmentId  { get; set; }

        [Display(Name = "Semester")]
        public int SemesterId  { get; set; }

        [Display(Name = "Grade Year")]
        public int GradeYearId  { get; set; }

        [Required]
        [Display(Name = "Course Data")]
        public long CourseDataId { get; set; }

        [Display(Name = "Select Examiner")]
        [Required]
        public long ExaminerId { get; set; }


        public IEnumerable<Department> Department { get; set; }
        public IEnumerable<Semester> Semester { get; set; }
        public IEnumerable<GradeYear> GradeYear { get; set; }
        public IEnumerable<CourseData> CourseData { get; set; }


        public IEnumerable<ExaminerData> ExaminerData { get; set; }
        public CourseTransaction CourseTransaction { get; set; }
        public StudentData StudentData { get; set; }


        [Display(Name = "Academic Year")]
        [Required]
        public DateTime? AcademicYear { get; set; }
        
    }
}

OnlineExamPlatform/Controllers/CourseTransactionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using OnlineExamPlatform.Models;
using OnlineExamPlatform.ViewModels;


namespace OnlineExamPlatform.Controllers
{
    public class CourseTransactionController : Controller
    {
        private OnXamsEntities _context;

        public CourseTransactionController()
        {
            _context = new OnXamsEntities();

        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: CourseTransaction
        //public ActionResult Index(string option, string search, int? pageNumber, string sort)
        //{
        //    ViewBag.SortByName = string.IsNullOrWhiteSpace(sort) ? "descending name" : "";


        //    var courseTransaction = _context.CourseTransactions
        //        .Where(c => c.IsDeleted == null || c.IsDeleted == false)
        //        .GroupBy(p =>
        //               new { p.CourseData.CourseName, p.AcademicYear })
        //        .Select(g => g.FirstOrDefault())
        //        .AsQueryable();

        //    if (option == "Course Name")
        //    {
        //        courseTransaction = courseTransaction
        //            .Where(c =>
        //                c.CourseData.CourseName.Contains(search) || search == null);
        //    }
        //    else if (option == "Examiner Name")
        //    {
        //        courseTransaction = courseTransaction
        //            .Where(c =>
        //                c.ExaminerData.FirstName.Contains(search) || search == null);

        //    }

        //    else
        //    {
        //        courseTransaction = courseTransaction
        //            .Where(c =>
        //                c.CourseData.CourseName.Contains(search) || search == null);

        //    }

        //    switch (sort)
        //    {
        //        case "descending name":
        //            courseTransaction = courseTransaction.OrderByDescending(c => c.CourseData.CourseName);
        //            break;
        //        default:
        //            courseTransaction = courseTransaction.OrderBy(c => c.CourseData.CourseName);
        //            break;

        //    }

        //    return View(courseTransaction.ToList().ToPagedList(pageNumber ?? 1, 20));
        //}

        public ActionResult Index()
        {
            var courseTransaction = _context.CourseTransactions
                .Where(c => c.IsDeleted == null || c.IsDeleted == false)
                .GroupBy(p =>
                    new { p.CourseData.CourseName, p.AcademicYear })
                .Select(g => g.FirstOrDefault())
                ;

            return View(courseTransaction);
        }






        [HttpGet]
        public ActionResult GetCourseByIds(int departmentId,int semesterId,int gradeId)
        {
          var course=  _context.CourseDatas.Where(c => c.DepartmentId == departmentId
                                            && c.SemesterId == semesterId
                                            && c.GradeYearID == gradeId).ToList();
          SelectList courseObj = new SelectList(course, "CourseDataID", "CourseName", 0);
            return Json(courseObj,JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult GetStudentByIds(int departmentId, int gradeId)
        {
            _context.Configuration.ProxyCreationEnabled = false;
            var student = _context.StudentDatas.Where(c => c.DepartmentId == departmentId
                                                           && c.GradeYearID == gradeId);
            student = student.Where(s => s.IsDeleted == false || s.IsDeleted == null);
            return Json(student, JsonRequestBehavior.AllowGet);
        }




        public ActionResult NewCourseTransaction()
        {
            var department = _context.Departments.ToList();
            var semester = _context.Semesters.ToList();
            var gradeYear = _context.GradeYears.ToList();
            var courseData = _context.CourseDatas
                .Where(c=>c.IsDeleted==false||c.IsDeleted==null)
                .ToList();

            var examiner = _context.ExaminerDatas.
                Where(e => e.IsDeleted == false || e.IsDeleted == null)
                .ToList();


            //***********************************
            //another solution

            //var examinersInDb = _context.ExaminerDatas.Where(e => e.IsDeleted == false || e.IsDeleted == null).Select(
            //    s => new
            //    {
            //        Text = s.FirstName + " " + s.MiddleName + " " + s.LastName,
            //        Value = s.ExaminerID
            //    }).ToList();

            //ViewBag.ExaminerList = new SelectList(examinersInDb, "Value", "Text");
            ////***********************************

            var model = new CourseTransactionViewModel()
            {
                Department = department,
                Semester = semester,
                GradeYear = gradeYear,
                CourseData = courseData,
                ExaminerData = examiner
            };

            return View("CourseTransactionForm", model);


          
        }



        
     




        /*################### Edit ###################*/
        public ActionResult Edit(Guid guid)
        {
            var courseTransactionInDb = _context.CourseTransactions
                .SingleOrDefault(c => c.CourseTransactionGUID == guid);
            if (courseTransactionInDb == null)
            {
                return HttpNotFound();
            }

            var courseInDb =
                _context.CourseDatas.SingleOrDefault(
                    c => c.CourseDataID == 
                         courseTransactionInDb.CourseDataID);
            if (courseInDb==null)
            {
                return HttpNotFound();
            }
            var departmentId = (int)courseInDb.DepartmentId;
            var semesterId = (int)courseInDb.SemesterId;
            var gradeYearId = (int)courseInDb.GradeYearID;
            var courseDataId = courseInDb.CourseDataID; 
            //var course = _context.CourseDatas.ToList();
            var department = _context.Departments.ToList();
            var semester = _context.Semesters.ToList();
            var gradeYear = _context.GradeYears.ToList();
            var examiner = _context.ExaminerDatas.Where(e => e.IsDeleted == false || e.IsDeleted == null).ToList();



            var model = new CourseTransactionViewModel()
            {
                DepartmentId = departmentId,
                SemesterId = semesterId,
                GradeYearId = gradeYearId,
                CourseDataId = courseDataId,
                CourseTransaction = courseTransactionInDb,
               
                ExaminerData = examiner,
                GradeYear = gradeYear,
                Semester = semester,
                Department = department,
                AcademicYear = courseTransactionInDb.AcademicYear



            };
            return View("CourseTransactionForm", model);
        }
















        /*################### Save ###################*/
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SaveCourseTransaction(CourseTransactionViewModel model)
        {
            var adminAuthentication = _context.UserAuthentications.SingleOrDefault
            (u =>
                u.Email.ToLower()
                    .Equals(User.Identity.Name));
            var flag = ModelState.IsValid;
            if (!flag)
            {
                return View("CourseTransactionForm", model);
            }
            //New Entity
            if (model.CourseTransaction.CourseTransactionGUID == null)
            {

                var studentInDb = _context.StudentDatas.Where(s => s.IsDeleted == null || s.IsDeleted == false)
                    .Where(s => s.DepartmentId == model.DepartmentId && s.GradeYearID == model.GradeYearId);
                var totalStudentCount = studentInDb.ToList().Count();
                foreach (var studentData in studentInDb.ToList())
                {
                    model.CourseTransaction.CourseTransactionGUID =Guid.NewGuid();
                    model.CourseTransaction.CourseDataID = model.CourseDataId;
                    model.CourseTransaction.AcademicYear = (DateTime)model.AcademicYear;
                    model.CourseTransaction.CreatedBy = adminAuthentication.Email;
                    model.CourseTransaction.CreatedDate = DateTime.Now;
                    model.CourseTransaction.StudentID = studentData.StudentID;
                    model.CourseTransaction.NumberOfStudents = totalStudentCount;
                    model.CourseTransaction.ExaminerID = model.ExaminerId;
                    if ((bool)studentData.IsPassed)
                    {
                        model.CourseTransaction.StudentStatus = "passed";
                    }
                    else
                    {
                        model.CourseTransaction.StudentStatus = "Failed";
                    }
                    _context.CourseTransactions.Add(model.CourseTransaction);
                    _context.SaveChanges();

                }
            }
            else
            {
                //Modify old Entity
                var courseTransactionInDb =
                    _context.CourseTransactions.SingleOrDefault(c =>
                        c.CourseTransactionGUID == model.CourseTransaction.CourseTransactionGUID);
                if (courseTransactionInDb == null)
                {
                    return HttpNotFound();
                }

                var id= courseTransactionInDb.CourseDataID;
               var courseTransactions= _context.CourseTransactions.Where(c => c.CourseDataID == id);
               foreach (var courseTransaction in courseTransactions.ToList())
               {
                   courseTransaction.ExaminerID = model.CourseTransaction.ExaminerID;

OnlineExamPlatform/Views/CourseTransaction/CourseTransactionForm.cshtml
@model OnlineExamPlatform.ViewModels.CourseTransactionViewModel
@{
    ViewBag.Title = "CourseTransactionForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">

            <div class="page-wrapper">
                <div class="page-body">
                    <div class="row">
                        <div class="col-md-12 col-lg-12">

                            @using (@Html.BeginForm("SaveCourseTransaction", "CourseTransaction"))
                            {
                                <div class="card">
                                    <div class="card-block">

                                        <div class="form-group" id="departmentDiv">
                                            @Html.LabelFor(m => m.DepartmentId)
                                            @Html.DropDownListFor(m => m.DepartmentId
                                                , new SelectList(Model.Department, "DepartmentId", "DepartmentName")
                                                , " -- Select a Department --"
                                                , new
                                                {
                                                    @class = "form-control"
                                                    ,
                                                    @id = "DepartmentId"

                                                })
                                            @Html.ValidationMessageFor(m => m.DepartmentId)
                                        </div>


                                        <div class="form-group" id="semesterDiv">

                                            @Html.LabelFor(m => m.SemesterId)
                                            @Html.DropDownListFor(m => m.SemesterId
                                                , new SelectList(Model.Semester, "SemesterId", "SemesterName")
                                                , " -- Select a Semester --"
                                                , new { @class = "form-control", @id = "SemesterId" })
                                            @Html.ValidationMessageFor(m => m.SemesterId)


                                        </div>

                                        <div class="form-group" id="gradeYearDiv">

                                            @Html.LabelFor(m => m.GradeYearId)
                                            @Html.DropDownListFor(m => m.GradeYearId
                                                , new SelectList(Model.GradeYear, "GradeYearId", "GradeYearName")
                                                , " -- Select a Grade Year --"
                                                , new { @class = "form-control", @id = "GradeYearId" })
                                            @Html.ValidationMessageFor(m => m.GradeYearId)


                                        </div>
                                        @{

                                        }
                                        <div class="form-group" id="courseDataDiv">
                                            @Html.LabelFor(m => m.CourseDataId)
                                            <select id="CourseDataId" name="CourseDataId" class="form-control"></select>
                                            @Html.ValidationMessageFor(m => m.CourseDataId)

                                        </div>

                                        <div class="form-group">
                                            
                                            @Html.LabelFor(m => m.ExaminerId)
                                            @Html.DropDownListFor(m => m.ExaminerId,
                                                new SelectList(Model.ExaminerData, "ExaminerId", "FullName"),
                                                "-- Select Examiner --"
                                                , new {@class = "form-control"})
                                            @Html.ValidationMessageFor(m => m.ExaminerId)
                                        </div>
                                        
                                   

                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AcademicYear)
                                            @Html.TextBoxFor(m => m.AcademicYear, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                                            @Html.ValidationMessageFor(m => m.AcademicYear)
                                        </div>



                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-block">
                                        <div class="table-responsive">
                                            <table class="table table-striped table-condensed  table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>@Html.DisplayName("#")</th>
                                                        <th>@Html.DisplayName("Full Name")</th>
                                                        <th>@Html.DisplayName("Success Status")</th>

                                                    </tr>
                                                </thead>


                                                <tbody id="StudentTable"></tbody>
                                            </table>
                                        </div>
                                        @Html.HiddenFor(c => c.CourseTransaction.CourseTransactionGUID)
                                        @Html.AntiForgeryToken()
                                        <button class="btn btn-primary" type="submit">Save</button>
                                        @Html.ActionLink("Cancel", "Index", "CourseTransaction", new { @class = "pull-right btn btn-danger" })
                                    </div>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@*Client Side Validation*@
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval");


    <script>


        $(document).ready(function () {
            console.log($("#DepartmentId").val());


            $("#semesterDiv").addClass("invisible");
            $("#gradeYearDiv").addClass("invisible");
            $("#courseDataDiv").addClass("invisible");

            enableSemester();
            enableGrade();
            enableCourse();




            getCourseById($("#DepartmentId").val(), $("#SemesterId").val(), $("#GradeYearId").val());
          
            getStudentByIds($("#DepartmentId").val(), $("#GradeYearId").val());


            $("#GradeYearId,#DepartmentId,#SemesterId").on('change', function () {
                getCourseById($("#DepartmentId").val(), $("#SemesterId").val(), $("#GradeYearId").val());
                getStudentByIds($("#DepartmentId").val(), $("#GradeYearId").val());

            });

















            function getCourseById(departmentIdd, semesterIdd, gradeIdd) {
                var message = "<option value='0'> There are no available Courses...</option>";
                $("#CourseDataId").html(message).show();
                var url = "/CourseTransaction/GetCourseByIds";
                $.ajax({
                    url: url,
                    cache: false,
                    data: {
                        departmentId: departmentIdd,
                        semesterId: semesterIdd,
                        gradeId: gradeIdd

                    },
                    type: "GET",
                    success: function (data) {
                        var markup = "<option value='0'>Select Course</option>";
                        for (var x = 0; x < data.length; x++) {
                            markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                            $("#CourseDataId").html(markup).show();
                        }
                        $("#CourseDataId").val(@Model.CourseDataId);
                    }
                    //,
                    //error: function (response) {
                    //    alert("error: " + response);
                    //}
                });
            }




            function getStudentByIds(departmentIdd, gradeIdd) {

                var url = "/CourseTransaction/GetStudentByIds";

                $.ajax({
                    url: url,
                    cache: false,
                    data: {
                        departmentId: departmentIdd,
                        gradeId: gradeIdd
                    },
                    type: "GET",
                    success: function (data) {
                        $("#StudentTable").empty();
                        $.each(data, function (i, item) {
                            var state = "Passed";
                            if (!item.IsPassed) {
                                state = "Failed";
                            }
                            var rows = "<tr>" +
                                "<td>" + (++i) + "</td>" +
                                "<td>" + item.FirstName + " " + item.MiddleName + " " + item.LastName + "</td>" + 

                                "<td> <span class=''>" + state + "</span></td>" +
                                +"</tr>";
                            $("#StudentTable").append(rows);
                        });
                    }
                    //,
                    //error:function(response) {
                    //    alert('error ' + response);
                    //}

                });
            }




            function enableSemester() {
                $("#DepartmentId").on('click',
                    function () {

                        if ($("#DepartmentId").val().length <= 0) {
                            $("#semesterDiv").addClass("invisible");
                            $("#gradeYearDiv").addClass("invisible");
                            $("#courseDataDiv").addClass("invisible");
                            $("#SemesterId").val("");
                            $("#GradeYearId").val("");
                            $("#CourseDataId").val("");
                        } else {
                            $("#semesterDiv").removeClass("invisible");

                        }
                    });
            }


            function enableGrade() {
                $("#SemesterId").on('click',
                    function () {

                        if ($("#SemesterId").val().length <= 0) {

                            $("#gradeYearDiv").addClass("invisible");
                            $("#courseDataDiv").addClass("invisible");
                            $("#GradeYearId").val("");
                            $("#CourseDataId").val("");
                        } else {

                            $("#gradeYearDiv").removeClass("invisible");

                        }
                    });
            }

            function enableCourse() {
                $("#GradeYearId").on('click',
                    function () {

                        if ($("#GradeYearId").val().length <= 0) {




                            $("#courseDataDiv").addClass("invisible");
                            $("#CourseDataId").val("");
                        } else {

                            $("#courseDataDiv").removeClass("invisible");

                        }
                    });
            }



        });


    </script>
}

OnlineExamPlatform/Views/CourseTransaction/Index.cshtml
@model IEnumerable<OnlineExamPlatform.Models.CourseTransaction>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var counter = 0;
}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">

            <div class="page-wrapper">
                <div class="page-body">


                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-block">

                                    @Html.ActionLink("New Course Transaction","NewCourseTransaction","CourseTransaction",new {@class="btn btn-primary btn-block text-center"})
                                </div>

                            </div>
                        </div>

                    </div>


                    <div class="row">


                        <div class="col-12">
                            <div class="card">
                                
                                <!--Schedule Table-->
                                <div class="card-block">

                                    <div class=" table-responsive">
                                       
                                            <table id="courseTransactionTable" class="table table-striped table-condensed  table-hover">


                                                <thead class="thead-inverse">
                                                    <tr>
                                                        <th>@Html.DisplayName("#")</th>
                                                        <th>@Html.DisplayName("Course Name")</th>
                                                       



                                                        <th>@Html.DisplayName("Examiner Name")</th>
                                                        <th>@Html.DisplayName("Academic Year")</th>
                                                        <th>@Html.DisplayName("Number Of Students")</th>
                                                        <th>@Html.DisplayName("Action")</th>

                                                    </tr>
                                                </thead>
                                              
                                                    @foreach (var c in Model)
                                                    {


                                                        <tr>
                                                            <td>@(++counter)</td>
                                                            <td>@Html.DisplayFor(m => c.CourseData.CourseName)</td>
                                                            <td>
                                                                @Html.DisplayFor(m => c.ExaminerData.FirstName)
                                                                @Html.DisplayFor(m => c.ExaminerData.MiddleName)
                                                                @Html.DisplayFor(m => c.ExaminerData.LastName)
                                                            </td>
            
                                                            <td>
                                                                @{
                                                                    var date = c.AcademicYear.Date.Year + 1;
                                                                }
                                                                @Html.DisplayFor(m => c.AcademicYear.Date.Year) / @date
                                                            </td>
                                                            <td>@Html.DisplayFor(m => c.NumberOfStudents)</td>
                                                            <td>

                                                                @Html.ActionLink(" ", "Delete", "CourseTransaction", new { guid = c.CourseTransactionGUID }, new { @class = "ti-trash", style = "color:Red;", onclick = "return confirm('Are you Sure to Delete');" })
                                                                @Html.ActionLink(" ", "Edit", "CourseTransaction", new { guid = c.CourseTransactionGUID }, new { @class = "ti-pencil-alt", style = "color:black;" })
                                                            </td>
                                                        </tr>
                                                    }

                                              

                                            </table>

                                        
                                      
                                    </div>
                                </div>


                            </div>

                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

</div>
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#courseTransactionTable").dataTable();
        });
    </script>
}